version: 2.1

executors:
  job-executor:
    docker:
      - image: basisregisters/build-agent:latest
      - image: mcr.microsoft.com/mssql/server:latest
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: E@syP@ssw0rd

jobs:
  build:
    executor: job-executor

    environment:
      MYGET_FEED: /F/basisregisters
      MYGET_FEED_USER: informatievlaanderen
      MYGET_HOST: https://informatievlaanderen.myget.org
      NUGET_HOST: https://www.nuget.org
      GIT_USERNAME: release-bot
      GIT_AUTHOR_NAME: release-bot
      GIT_COMMITTER_NAME: release-bot
      GIT_EMAIL: informatie.vlaanderen@vlaanderen.be
      GIT_AUTHOR_EMAIL: informatie.vlaanderen@vlaanderen.be
      GIT_COMMITTER_EMAIL: informatie.vlaanderen@vlaanderen.be
      CONFLUENCE_USERNAME: david.cumps@kb.vlaanderen.be
      SA_PASSWORD: E@syP@ssw0rd
      CI: true

    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - restore_cache:
          name: Restore Paket  cache
          keys:
            - v1-paket-{{ arch }}-{{ .Branch }}-{{ checksum "paket.dependencies" }}
            - v1-paket-{{ arch }}-{{ .Branch }}-
            - v1-paket-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install NPM dependencies (master)
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              npm install;
            fi

      - run:
          name: Run Semantic Release (master)
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              npx semantic-release;
            fi

      - run:
          name: Run Build (non-master)
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ];
            then
              echo 'export CI=true' >> ~/.bashrc
              source ~/.bashrc
              ./build.sh;
            fi

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - save_cache:
          name: Save Paket cache
          key: v1-paket-{{ arch }}-{{ .Branch }}-{{ checksum "paket.dependencies" }}
          paths:
            - ~/.nuget/packages
            - packages

      - persist_to_workspace:
          root: workspace
          paths:
            - semver

  push_to_production:
    executor: job-executor

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker

      - run:
          name: Copy Docker images to production
          command: |
            SEMVER=$(cat /tmp/workspace/semver)
            eval $(AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID     AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY     aws ecr get-login --no-include-email --region eu-west-1 | sed 's|https://||')
            eval $(AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRD AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRD aws ecr get-login --no-include-email --region eu-west-1 | sed 's|https://||')

            docker pull $BUILD_DOCKER_REGISTRY/public-service-registry/api:$SEMVER
            docker tag  $BUILD_DOCKER_REGISTRY/public-service-registry/api:$SEMVER $BUILD_DOCKER_REGISTRY_PRD/public-service-registry/api:$SEMVER
            docker push $BUILD_DOCKER_REGISTRY_PRD/public-service-registry/api:$SEMVER

            docker pull $BUILD_DOCKER_REGISTRY/public-service-registry/projector:$SEMVER
            docker tag  $BUILD_DOCKER_REGISTRY/public-service-registry/projector:$SEMVER $BUILD_DOCKER_REGISTRY_PRD/public-service-registry/projector:$SEMVER
            docker push $BUILD_DOCKER_REGISTRY_PRD/public-service-registry/projector:$SEMVER

            docker pull $BUILD_DOCKER_REGISTRY/public-service-registry/batch-orafin:$SEMVER
            docker tag  $BUILD_DOCKER_REGISTRY/public-service-registry/batch-orafin:$SEMVER $BUILD_DOCKER_REGISTRY_PRD/public-service-registry/batch-orafin:$SEMVER
            docker push $BUILD_DOCKER_REGISTRY_PRD/public-service-registry/batch-orafin:$SEMVER

            docker pull $BUILD_DOCKER_REGISTRY/public-service-registry/ui:$SEMVER
            docker tag  $BUILD_DOCKER_REGISTRY/public-service-registry/ui:$SEMVER $BUILD_DOCKER_REGISTRY_PRD/public-service-registry/ui:$SEMVER
            docker push $BUILD_DOCKER_REGISTRY_PRD/public-service-registry/ui:$SEMVER

workflows:
  version: 2
  build_and_push_to_production:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - push_to_production:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
